apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_NAME}-service
  namespace: oms
spec:
  selector:
    application: ${CI_PROJECT_NAME}-service
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31521
